language: go

go:
  - 1.11.x

sudo: false

services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep status
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - sh hack/build.sh

script:
  - echo "tests..."
